# Generated by Django 6.0.6 on 2026-06-28 10:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('saved', 'Сохранено'), ('applied', 'Откликнулся'), ('interview', 'Интервью'), ('offer', 'Оффер'), ('rejected', 'Отказ')], default='saved', max_length=20)),
                ('salary', models.PositiveIntegerField(blank=True, null=True)),
                ('url', models.URLField(blank=True)),
                ('applied_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вакансия',
                'verbose_name_plural': 'Вакансии',
                'db_table': 'vacancies',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='vacancies_user_id_0ce86c_idx')],
            },
        ),
    ]
